// Generated by Bisonc++ V4.13.01 on Sat, 18 Feb 2017 20:33:41 +0530

// $insert class.ih
#include "parser.ih"

// The FIRST element of SR arrays shown below uses `d_type', defining the
// state's type, and `d_lastIdx' containing the last element's index. If
// d_lastIdx contains the REQ_TOKEN bitflag (see below) then the state needs
// a token: if in this state d_token__ is _UNDETERMINED_, nextToken() will be
// called

// The LAST element of SR arrays uses `d_token' containing the last retrieved
// token to speed up the (linear) seach.  Except for the first element of SR
// arrays, the field `d_action' is used to determine what to do next. If
// positive, it represents the next state (used with SHIFT); if zero, it
// indicates `ACCEPT', if negative, -d_action represents the number of the
// rule to reduce to.

// `lookup()' tries to find d_token__ in the current SR array. If it fails, and
// there is no default reduction UNEXPECTED_TOKEN__ is thrown, which is then
// caught by the error-recovery function.

// The error-recovery function will pop elements off the stack until a state
// having bit flag ERR_ITEM is found. This state has a transition on _error_
// which is applied. In this _error_ state, while the current token is not a
// proper continuation, new tokens are obtained by nextToken(). If such a
// token is found, error recovery is successful and the token is
// handled according to the error state's SR table and parsing continues.
// During error recovery semantic actions are ignored.

// A state flagged with the DEF_RED flag will perform a default
// reduction if no other continuations are available for the current token.

// The ACCEPT STATE never shows a default reduction: when it is reached the
// parser returns ACCEPT(). During the grammar
// analysis phase a default reduction may have been defined, but it is
// removed during the state-definition phase.

// So:
//      s_x[] = 
//      {
//                  [_field_1_]         [_field_2_]
//
// First element:   {state-type,        idx of last element},
// Other elements:  {required token,    action to perform},
//                                      ( < 0: reduce, 
//                                          0: ACCEPT,
//                                        > 0: next state)
// Last element:    {set to d_token__,    action to perform}
//      }

// When the --thread-safe option is specified, all static data are defined as
// const. If --thread-safe is not provided, the state-tables are not defined
// as const, since the lookup() function below will modify them


namespace // anonymous
{
    char const author[] = "Frank B. Brokken (f.b.brokken@rug.nl)";

    enum 
    {
        STACK_EXPANSION = 5     // size to expand the state-stack with when
                                // full
    };

    enum ReservedTokens
    {
        PARSE_ACCEPT     = 0,   // `ACCEPT' TRANSITION
        _UNDETERMINED_   = -2,
        _EOF_            = -1,
        _error_          = 256
    };
    enum StateType       // modify statetype/data.cc when this enum changes
    {
        NORMAL,
        ERR_ITEM,
        REQ_TOKEN,
        ERR_REQ,    // ERR_ITEM | REQ_TOKEN
        DEF_RED,    // state having default reduction
        ERR_DEF,    // ERR_ITEM | DEF_RED
        REQ_DEF,    // REQ_TOKEN | DEF_RED
        ERR_REQ_DEF // ERR_ITEM | REQ_TOKEN | DEF_RED
    };    
    struct PI__     // Production Info
    {
        size_t d_nonTerm; // identification number of this production's
                            // non-terminal 
        size_t d_size;    // number of elements in this production 
    };

    struct SR__     // Shift Reduce info, see its description above
    {
        union
        {
            int _field_1_;      // initializer, allowing initializations 
                                // of the SR s_[] arrays
            int d_type;
            int d_token;
        };
        union
        {
            int _field_2_;

            int d_lastIdx;          // if negative, the state uses SHIFT
            int d_action;           // may be negative (reduce), 
                                    // postive (shift), or 0 (accept)
            size_t d_errorState;    // used with Error states
        };
    };

    // $insert staticdata
    
// Productions Info Records:
PI__ const s_productionInfo[] = 
{
     {0, 0}, // not used: reduction values are negative
     {299, 2}, // 1: program ->  declaration_list procedure_definition
     {300, 1}, // 2: declaration_list ->  procedure_declaration
     {300, 2}, // 3: declaration_list ->  variable_declaration_list procedure_declaration
     {300, 2}, // 4: declaration_list ->  procedure_declaration variable_declaration_list
     {302, 5}, // 5: procedure_declaration (VOID) ->  VOID NAME '(' ')' ';'
     {301, 9}, // 6: procedure_definition (NAME) ->  NAME '(' ')' #0001 '{' optional_variable_declaration_list #0002 statement_list '}'
     {303, 0}, // 7: #0001 ->  <empty>
     {304, 0}, // 8: #0002 ->  <empty>
     {305, 0}, // 9: optional_variable_declaration_list ->  <empty>
     {305, 1}, // 10: optional_variable_declaration_list ->  variable_declaration_list
     {306, 1}, // 11: variable_declaration_list ->  variable_declaration
     {306, 2}, // 12: variable_declaration_list ->  variable_declaration_list variable_declaration
     {307, 2}, // 13: variable_declaration (';') ->  declaration ';'
     {308, 2}, // 14: declaration (INTEGER) ->  INTEGER int_declaration_names_list
     {308, 2}, // 15: declaration (FLOAT) ->  FLOAT float_declaration_names_list
     {309, 1}, // 16: int_declaration_names_list (NAME) ->  NAME
     {309, 3}, // 17: int_declaration_names_list (',') ->  int_declaration_names_list ',' NAME
     {310, 1}, // 18: float_declaration_names_list (NAME) ->  NAME
     {310, 3}, // 19: float_declaration_names_list (',') ->  float_declaration_names_list ',' NAME
     {311, 0}, // 20: statement_list ->  <empty>
     {311, 2}, // 21: statement_list ->  statement_list statement
     {312, 1}, // 22: statement ->  assignment_statement
     {312, 1}, // 23: statement ->  iteration_statement
     {312, 1}, // 24: statement ->  selection_statement
     {313, 5}, // 25: selection_statement (IF) ->  IF '(' boolean_expression_term ')' exp_body
     {313, 7}, // 26: selection_statement (WASH) ->  IF '(' boolean_expression_term ')' exp_body ELSE exp_body
     {314, 1}, // 27: exp_body ->  statement
     {314, 3}, // 28: exp_body ('{') ->  '{' statement_list '}'
     {315, 5}, // 29: iteration_statement (WHILE) ->  WHILE '(' boolean_expression_term ')' exp_body
     {315, 6}, // 30: iteration_statement (DO) ->  DO exp_body WHILE '(' boolean_expression_term ')'
     {316, 1}, // 31: boolean_expression_term ->  relational_expression
     {316, 1}, // 32: boolean_expression_term ->  boolean_expression
     {316, 3}, // 33: boolean_expression_term ('(') ->  '(' boolean_expression_term ')'
     {317, 3}, // 34: boolean_expression (AND) ->  boolean_expression_term AND boolean_expression_term
     {317, 3}, // 35: boolean_expression (OR) ->  boolean_expression_term OR boolean_expression_term
     {317, 2}, // 36: boolean_expression (NOT) ->  NOT boolean_expression_term
     {318, 3}, // 37: relational_expression (LE) ->  operand LE operand
     {318, 3}, // 38: relational_expression (LT) ->  operand LT operand
     {318, 3}, // 39: relational_expression (EQ) ->  operand EQ operand
     {318, 3}, // 40: relational_expression (NE) ->  operand NE operand
     {318, 3}, // 41: relational_expression (GE) ->  operand GE operand
     {318, 3}, // 42: relational_expression (GT) ->  operand GT operand
     {319, 4}, // 43: assignment_statement (ASSIGN) ->  variable ASSIGN arith_expression ';'
     {320, 3}, // 44: arith_expression ('+') ->  operand '+' operand
     {320, 3}, // 45: arith_expression ('-') ->  operand '-' operand
     {320, 3}, // 46: arith_expression ('*') ->  operand '*' operand
     {320, 3}, // 47: arith_expression ('/') ->  operand '/' operand
     {320, 5}, // 48: arith_expression ('?') ->  boolean_expression_term '?' operand ':' operand
     {320, 2}, // 49: arith_expression (UMINUS) ->  '-' operand
     {320, 3}, // 50: arith_expression ('(') ->  '(' operand ')'
     {320, 1}, // 51: arith_expression ->  expression_term
     {321, 1}, // 52: operand ->  arith_expression
     {322, 1}, // 53: expression_term ->  variable
     {322, 1}, // 54: expression_term ->  constant
     {323, 1}, // 55: variable (NAME) ->  NAME
     {324, 1}, // 56: constant (INTEGER_NUMBER) ->  INTEGER_NUMBER
     {324, 1}, // 57: constant (DOUBLE_NUMBER) ->  DOUBLE_NUMBER
     {325, 1}, // 58: program_$ ->  program
};

// State info and SR__ transitions for each state.


SR__ s_0[] =
{
    { { REQ_TOKEN}, { 10} },                             
    { {       299}, {  1} }, // program                  
    { {       300}, {  2} }, // declaration_list         
    { {       302}, {  3} }, // procedure_declaration    
    { {       306}, {  4} }, // variable_declaration_list
    { {       263}, {  5} }, // VOID                     
    { {       307}, {  6} }, // variable_declaration     
    { {       308}, {  7} }, // declaration              
    { {       260}, {  8} }, // INTEGER                  
    { {       261}, {  9} }, // FLOAT                    
    { {         0}, {  0} },                             
};

SR__ s_1[] =
{
    { { REQ_TOKEN}, {            2} }, 
    { {     _EOF_}, { PARSE_ACCEPT} }, 
    { {         0}, {            0} }, 
};

SR__ s_2[] =
{
    { { REQ_TOKEN}, {  3} },                        
    { {       301}, { 10} }, // procedure_definition
    { {       259}, { 11} }, // NAME                
    { {         0}, {  0} },                        
};

SR__ s_3[] =
{
    { { REQ_DEF}, {  6} },                             
    { {     306}, { 12} }, // variable_declaration_list
    { {     307}, {  6} }, // variable_declaration     
    { {     308}, {  7} }, // declaration              
    { {     260}, {  8} }, // INTEGER                  
    { {     261}, {  9} }, // FLOAT                    
    { {       0}, { -2} },                             
};

SR__ s_4[] =
{
    { { REQ_TOKEN}, {  7} },                         
    { {       302}, { 13} }, // procedure_declaration
    { {       307}, { 14} }, // variable_declaration 
    { {       263}, {  5} }, // VOID                 
    { {       308}, {  7} }, // declaration          
    { {       260}, {  8} }, // INTEGER              
    { {       261}, {  9} }, // FLOAT                
    { {         0}, {  0} },                         
};

SR__ s_5[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       259}, { 15} }, // NAME
    { {         0}, {  0} },        
};

SR__ s_6[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -11} }, 
};

SR__ s_7[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        59}, { 16} }, // ';'
    { {         0}, {  0} },       
};

SR__ s_8[] =
{
    { { REQ_TOKEN}, {  3} },                              
    { {       309}, { 17} }, // int_declaration_names_list
    { {       259}, { 18} }, // NAME                      
    { {         0}, {  0} },                              
};

SR__ s_9[] =
{
    { { REQ_TOKEN}, {  3} },                                
    { {       310}, { 19} }, // float_declaration_names_list
    { {       259}, { 20} }, // NAME                        
    { {         0}, {  0} },                                
};

SR__ s_10[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -1} }, 
};

SR__ s_11[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        40}, { 21} }, // '('
    { {         0}, {  0} },       
};

SR__ s_12[] =
{
    { { REQ_DEF}, {  5} },                        
    { {     307}, { 14} }, // variable_declaration
    { {     308}, {  7} }, // declaration         
    { {     260}, {  8} }, // INTEGER             
    { {     261}, {  9} }, // FLOAT               
    { {       0}, { -4} },                        
};

SR__ s_13[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -3} }, 
};

SR__ s_14[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -12} }, 
};

SR__ s_15[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        40}, { 22} }, // '('
    { {         0}, {  0} },       
};

SR__ s_16[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -13} }, 
};

SR__ s_17[] =
{
    { { REQ_DEF}, {   2} },       
    { {      44}, {  23} }, // ','
    { {       0}, { -14} },       
};

SR__ s_18[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -16} }, 
};

SR__ s_19[] =
{
    { { REQ_DEF}, {   2} },       
    { {      44}, {  24} }, // ','
    { {       0}, { -15} },       
};

SR__ s_20[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -18} }, 
};

SR__ s_21[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        41}, { 25} }, // ')'
    { {         0}, {  0} },       
};

SR__ s_22[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        41}, { 26} }, // ')'
    { {         0}, {  0} },       
};

SR__ s_23[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       259}, { 27} }, // NAME
    { {         0}, {  0} },        
};

SR__ s_24[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       259}, { 28} }, // NAME
    { {         0}, {  0} },        
};

SR__ s_25[] =
{
    { { DEF_RED}, {  2} },         
    { {     303}, { 29} }, // #0001
    { {       0}, { -7} },         
};

SR__ s_26[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        59}, { 30} }, // ';'
    { {         0}, {  0} },       
};

SR__ s_27[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -17} }, 
};

SR__ s_28[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -19} }, 
};

SR__ s_29[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {       123}, { 31} }, // '{'
    { {         0}, {  0} },       
};

SR__ s_30[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -5} }, 
};

SR__ s_31[] =
{
    { { REQ_DEF}, {  7} },                                      
    { {     305}, { 32} }, // optional_variable_declaration_list
    { {     306}, { 33} }, // variable_declaration_list         
    { {     307}, {  6} }, // variable_declaration              
    { {     308}, {  7} }, // declaration                       
    { {     260}, {  8} }, // INTEGER                           
    { {     261}, {  9} }, // FLOAT                             
    { {       0}, { -9} },                                      
};

SR__ s_32[] =
{
    { { DEF_RED}, {  2} },         
    { {     304}, { 34} }, // #0002
    { {       0}, { -8} },         
};

SR__ s_33[] =
{
    { { REQ_DEF}, {   5} },                        
    { {     307}, {  14} }, // variable_declaration
    { {     308}, {   7} }, // declaration         
    { {     260}, {   8} }, // INTEGER             
    { {     261}, {   9} }, // FLOAT               
    { {       0}, { -10} },                        
};

SR__ s_34[] =
{
    { { DEF_RED}, {   2} },                  
    { {     311}, {  35} }, // statement_list
    { {       0}, { -20} },                  
};

SR__ s_35[] =
{
    { { REQ_TOKEN}, { 11} },                        
    { {       125}, { 36} }, // '}'                 
    { {       312}, { 37} }, // statement           
    { {       319}, { 38} }, // assignment_statement
    { {       315}, { 39} }, // iteration_statement 
    { {       313}, { 40} }, // selection_statement 
    { {       323}, { 41} }, // variable            
    { {       274}, { 42} }, // WHILE               
    { {       275}, { 43} }, // DO                  
    { {       273}, { 44} }, // IF                  
    { {       259}, { 45} }, // NAME                
    { {         0}, {  0} },                        
};

SR__ s_36[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -6} }, 
};

SR__ s_37[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -21} }, 
};

SR__ s_38[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -22} }, 
};

SR__ s_39[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -23} }, 
};

SR__ s_40[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -24} }, 
};

SR__ s_41[] =
{
    { { REQ_TOKEN}, {  2} },          
    { {       262}, { 46} }, // ASSIGN
    { {         0}, {  0} },          
};

SR__ s_42[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        40}, { 47} }, // '('
    { {         0}, {  0} },       
};

SR__ s_43[] =
{
    { { REQ_TOKEN}, { 12} },                        
    { {       314}, { 48} }, // exp_body            
    { {       312}, { 49} }, // statement           
    { {       123}, { 50} }, // '{'                 
    { {       319}, { 38} }, // assignment_statement
    { {       315}, { 39} }, // iteration_statement 
    { {       313}, { 40} }, // selection_statement 
    { {       323}, { 41} }, // variable            
    { {       274}, { 42} }, // WHILE               
    { {       275}, { 43} }, // DO                  
    { {       273}, { 44} }, // IF                  
    { {       259}, { 45} }, // NAME                
    { {         0}, {  0} },                        
};

SR__ s_44[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        40}, { 51} }, // '('
    { {         0}, {  0} },       
};

SR__ s_45[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -55} }, 
};

SR__ s_46[] =
{
    { { REQ_TOKEN}, { 15} },                           
    { {       320}, { 52} }, // arith_expression       
    { {       321}, { 53} }, // operand                
    { {       316}, { 54} }, // boolean_expression_term
    { {        45}, { 55} }, // '-'                    
    { {        40}, { 56} }, // '('                    
    { {       322}, { 57} }, // expression_term        
    { {       318}, { 58} }, // relational_expression  
    { {       317}, { 59} }, // boolean_expression     
    { {       323}, { 60} }, // variable               
    { {       324}, { 61} }, // constant               
    { {       264}, { 62} }, // NOT                    
    { {       259}, { 45} }, // NAME                   
    { {       257}, { 63} }, // INTEGER_NUMBER         
    { {       258}, { 64} }, // DOUBLE_NUMBER          
    { {         0}, {  0} },                           
};

SR__ s_47[] =
{
    { { REQ_TOKEN}, { 15} },                           
    { {       316}, { 65} }, // boolean_expression_term
    { {       318}, { 58} }, // relational_expression  
    { {       317}, { 59} }, // boolean_expression     
    { {        40}, { 56} }, // '('                    
    { {       321}, { 53} }, // operand                
    { {       264}, { 62} }, // NOT                    
    { {       320}, { 66} }, // arith_expression       
    { {        45}, { 55} }, // '-'                    
    { {       322}, { 57} }, // expression_term        
    { {       323}, { 60} }, // variable               
    { {       324}, { 61} }, // constant               
    { {       259}, { 45} }, // NAME                   
    { {       257}, { 63} }, // INTEGER_NUMBER         
    { {       258}, { 64} }, // DOUBLE_NUMBER          
    { {         0}, {  0} },                           
};

SR__ s_48[] =
{
    { { REQ_TOKEN}, {  2} },         
    { {       274}, { 67} }, // WHILE
    { {         0}, {  0} },         
};

SR__ s_49[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -27} }, 
};

SR__ s_50[] =
{
    { { DEF_RED}, {   2} },                  
    { {     311}, {  68} }, // statement_list
    { {       0}, { -20} },                  
};

SR__ s_51[] =
{
    { { REQ_TOKEN}, { 15} },                           
    { {       316}, { 69} }, // boolean_expression_term
    { {       318}, { 58} }, // relational_expression  
    { {       317}, { 59} }, // boolean_expression     
    { {        40}, { 56} }, // '('                    
    { {       321}, { 53} }, // operand                
    { {       264}, { 62} }, // NOT                    
    { {       320}, { 66} }, // arith_expression       
    { {        45}, { 55} }, // '-'                    
    { {       322}, { 57} }, // expression_term        
    { {       323}, { 60} }, // variable               
    { {       324}, { 61} }, // constant               
    { {       259}, { 45} }, // NAME                   
    { {       257}, { 63} }, // INTEGER_NUMBER         
    { {       258}, { 64} }, // DOUBLE_NUMBER          
    { {         0}, {  0} },                           
};

SR__ s_52[] =
{
    { { REQ_DEF}, {   2} },       
    { {      59}, {  70} }, // ';'
    { {       0}, { -52} },       
};

SR__ s_53[] =
{
    { { REQ_TOKEN}, { 11} },       
    { {        43}, { 71} }, // '+'
    { {        45}, { 72} }, // '-'
    { {        42}, { 73} }, // '*'
    { {        47}, { 74} }, // '/'
    { {       266}, { 75} }, // LE 
    { {       269}, { 76} }, // LT 
    { {       267}, { 77} }, // EQ 
    { {       268}, { 78} }, // NE 
    { {       265}, { 79} }, // GE 
    { {       270}, { 80} }, // GT 
    { {         0}, {  0} },       
};

SR__ s_54[] =
{
    { { REQ_TOKEN}, {  4} },       
    { {        63}, { 81} }, // '?'
    { {       271}, { 82} }, // AND
    { {       272}, { 83} }, // OR 
    { {         0}, {  0} },       
};

SR__ s_55[] =
{
    { { REQ_TOKEN}, { 15} },                           
    { {       321}, { 84} }, // operand                
    { {       320}, { 66} }, // arith_expression       
    { {       316}, { 54} }, // boolean_expression_term
    { {        45}, { 55} }, // '-'                    
    { {        40}, { 56} }, // '('                    
    { {       322}, { 57} }, // expression_term        
    { {       318}, { 58} }, // relational_expression  
    { {       317}, { 59} }, // boolean_expression     
    { {       323}, { 60} }, // variable               
    { {       324}, { 61} }, // constant               
    { {       264}, { 62} }, // NOT                    
    { {       259}, { 45} }, // NAME                   
    { {       257}, { 63} }, // INTEGER_NUMBER         
    { {       258}, { 64} }, // DOUBLE_NUMBER          
    { {         0}, {  0} },                           
};

SR__ s_56[] =
{
    { { REQ_TOKEN}, { 15} },                           
    { {       321}, { 85} }, // operand                
    { {       316}, { 86} }, // boolean_expression_term
    { {       320}, { 66} }, // arith_expression       
    { {       318}, { 58} }, // relational_expression  
    { {       317}, { 59} }, // boolean_expression     
    { {        40}, { 56} }, // '('                    
    { {        45}, { 55} }, // '-'                    
    { {       322}, { 57} }, // expression_term        
    { {       264}, { 62} }, // NOT                    
    { {       323}, { 60} }, // variable               
    { {       324}, { 61} }, // constant               
    { {       259}, { 45} }, // NAME                   
    { {       257}, { 63} }, // INTEGER_NUMBER         
    { {       258}, { 64} }, // DOUBLE_NUMBER          
    { {         0}, {  0} },                           
};

SR__ s_57[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -51} }, 
};

SR__ s_58[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -31} }, 
};

SR__ s_59[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -32} }, 
};

SR__ s_60[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -53} }, 
};

SR__ s_61[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -54} }, 
};

SR__ s_62[] =
{
    { { REQ_TOKEN}, { 15} },                           
    { {       316}, { 87} }, // boolean_expression_term
    { {       318}, { 58} }, // relational_expression  
    { {       317}, { 59} }, // boolean_expression     
    { {        40}, { 56} }, // '('                    
    { {       321}, { 53} }, // operand                
    { {       264}, { 62} }, // NOT                    
    { {       320}, { 66} }, // arith_expression       
    { {        45}, { 55} }, // '-'                    
    { {       322}, { 57} }, // expression_term        
    { {       323}, { 60} }, // variable               
    { {       324}, { 61} }, // constant               
    { {       259}, { 45} }, // NAME                   
    { {       257}, { 63} }, // INTEGER_NUMBER         
    { {       258}, { 64} }, // DOUBLE_NUMBER          
    { {         0}, {  0} },                           
};

SR__ s_63[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -56} }, 
};

SR__ s_64[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -57} }, 
};

SR__ s_65[] =
{
    { { REQ_TOKEN}, {  5} },       
    { {        41}, { 88} }, // ')'
    { {       271}, { 82} }, // AND
    { {       272}, { 83} }, // OR 
    { {        63}, { 81} }, // '?'
    { {         0}, {  0} },       
};

SR__ s_66[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -52} }, 
};

SR__ s_67[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        40}, { 89} }, // '('
    { {         0}, {  0} },       
};

SR__ s_68[] =
{
    { { REQ_TOKEN}, { 11} },                        
    { {       125}, { 90} }, // '}'                 
    { {       312}, { 37} }, // statement           
    { {       319}, { 38} }, // assignment_statement
    { {       315}, { 39} }, // iteration_statement 
    { {       313}, { 40} }, // selection_statement 
    { {       323}, { 41} }, // variable            
    { {       274}, { 42} }, // WHILE               
    { {       275}, { 43} }, // DO                  
    { {       273}, { 44} }, // IF                  
    { {       259}, { 45} }, // NAME                
    { {         0}, {  0} },                        
};

SR__ s_69[] =
{
    { { REQ_TOKEN}, {  5} },       
    { {        41}, { 91} }, // ')'
    { {       271}, { 82} }, // AND
    { {       272}, { 83} }, // OR 
    { {        63}, { 81} }, // '?'
    { {         0}, {  0} },       
};

SR__ s_70[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -43} }, 
};

SR__ s_71[] =
{
    { { REQ_TOKEN}, { 15} },                           
    { {       321}, { 92} }, // operand                
    { {       320}, { 66} }, // arith_expression       
    { {       316}, { 54} }, // boolean_expression_term
    { {        45}, { 55} }, // '-'                    
    { {        40}, { 56} }, // '('                    
    { {       322}, { 57} }, // expression_term        
    { {       318}, { 58} }, // relational_expression  
    { {       317}, { 59} }, // boolean_expression     
    { {       323}, { 60} }, // variable               
    { {       324}, { 61} }, // constant               
    { {       264}, { 62} }, // NOT                    
    { {       259}, { 45} }, // NAME                   
    { {       257}, { 63} }, // INTEGER_NUMBER         
    { {       258}, { 64} }, // DOUBLE_NUMBER          
    { {         0}, {  0} },                           
};

SR__ s_72[] =
{
    { { REQ_TOKEN}, { 15} },                           
    { {       321}, { 93} }, // operand                
    { {       320}, { 66} }, // arith_expression       
    { {       316}, { 54} }, // boolean_expression_term
    { {        45}, { 55} }, // '-'                    
    { {        40}, { 56} }, // '('                    
    { {       322}, { 57} }, // expression_term        
    { {       318}, { 58} }, // relational_expression  
    { {       317}, { 59} }, // boolean_expression     
    { {       323}, { 60} }, // variable               
    { {       324}, { 61} }, // constant               
    { {       264}, { 62} }, // NOT                    
    { {       259}, { 45} }, // NAME                   
    { {       257}, { 63} }, // INTEGER_NUMBER         
    { {       258}, { 64} }, // DOUBLE_NUMBER          
    { {         0}, {  0} },                           
};

SR__ s_73[] =
{
    { { REQ_TOKEN}, { 15} },                           
    { {       321}, { 94} }, // operand                
    { {       320}, { 66} }, // arith_expression       
    { {       316}, { 54} }, // boolean_expression_term
    { {        45}, { 55} }, // '-'                    
    { {        40}, { 56} }, // '('                    
    { {       322}, { 57} }, // expression_term        
    { {       318}, { 58} }, // relational_expression  
    { {       317}, { 59} }, // boolean_expression     
    { {       323}, { 60} }, // variable               
    { {       324}, { 61} }, // constant               
    { {       264}, { 62} }, // NOT                    
    { {       259}, { 45} }, // NAME                   
    { {       257}, { 63} }, // INTEGER_NUMBER         
    { {       258}, { 64} }, // DOUBLE_NUMBER          
    { {         0}, {  0} },                           
};

SR__ s_74[] =
{
    { { REQ_TOKEN}, { 15} },                           
    { {       321}, { 95} }, // operand                
    { {       320}, { 66} }, // arith_expression       
    { {       316}, { 54} }, // boolean_expression_term
    { {        45}, { 55} }, // '-'                    
    { {        40}, { 56} }, // '('                    
    { {       322}, { 57} }, // expression_term        
    { {       318}, { 58} }, // relational_expression  
    { {       317}, { 59} }, // boolean_expression     
    { {       323}, { 60} }, // variable               
    { {       324}, { 61} }, // constant               
    { {       264}, { 62} }, // NOT                    
    { {       259}, { 45} }, // NAME                   
    { {       257}, { 63} }, // INTEGER_NUMBER         
    { {       258}, { 64} }, // DOUBLE_NUMBER          
    { {         0}, {  0} },                           
};

SR__ s_75[] =
{
    { { REQ_TOKEN}, { 15} },                           
    { {       321}, { 96} }, // operand                
    { {       320}, { 66} }, // arith_expression       
    { {       316}, { 54} }, // boolean_expression_term
    { {        45}, { 55} }, // '-'                    
    { {        40}, { 56} }, // '('                    
    { {       322}, { 57} }, // expression_term        
    { {       318}, { 58} }, // relational_expression  
    { {       317}, { 59} }, // boolean_expression     
    { {       323}, { 60} }, // variable               
    { {       324}, { 61} }, // constant               
    { {       264}, { 62} }, // NOT                    
    { {       259}, { 45} }, // NAME                   
    { {       257}, { 63} }, // INTEGER_NUMBER         
    { {       258}, { 64} }, // DOUBLE_NUMBER          
    { {         0}, {  0} },                           
};

SR__ s_76[] =
{
    { { REQ_TOKEN}, { 15} },                           
    { {       321}, { 97} }, // operand                
    { {       320}, { 66} }, // arith_expression       
    { {       316}, { 54} }, // boolean_expression_term
    { {        45}, { 55} }, // '-'                    
    { {        40}, { 56} }, // '('                    
    { {       322}, { 57} }, // expression_term        
    { {       318}, { 58} }, // relational_expression  
    { {       317}, { 59} }, // boolean_expression     
    { {       323}, { 60} }, // variable               
    { {       324}, { 61} }, // constant               
    { {       264}, { 62} }, // NOT                    
    { {       259}, { 45} }, // NAME                   
    { {       257}, { 63} }, // INTEGER_NUMBER         
    { {       258}, { 64} }, // DOUBLE_NUMBER          
    { {         0}, {  0} },                           
};

SR__ s_77[] =
{
    { { REQ_TOKEN}, { 15} },                           
    { {       321}, { 98} }, // operand                
    { {       320}, { 66} }, // arith_expression       
    { {       316}, { 54} }, // boolean_expression_term
    { {        45}, { 55} }, // '-'                    
    { {        40}, { 56} }, // '('                    
    { {       322}, { 57} }, // expression_term        
    { {       318}, { 58} }, // relational_expression  
    { {       317}, { 59} }, // boolean_expression     
    { {       323}, { 60} }, // variable               
    { {       324}, { 61} }, // constant               
    { {       264}, { 62} }, // NOT                    
    { {       259}, { 45} }, // NAME                   
    { {       257}, { 63} }, // INTEGER_NUMBER         
    { {       258}, { 64} }, // DOUBLE_NUMBER          
    { {         0}, {  0} },                           
};

SR__ s_78[] =
{
    { { REQ_TOKEN}, { 15} },                           
    { {       321}, { 99} }, // operand                
    { {       320}, { 66} }, // arith_expression       
    { {       316}, { 54} }, // boolean_expression_term
    { {        45}, { 55} }, // '-'                    
    { {        40}, { 56} }, // '('                    
    { {       322}, { 57} }, // expression_term        
    { {       318}, { 58} }, // relational_expression  
    { {       317}, { 59} }, // boolean_expression     
    { {       323}, { 60} }, // variable               
    { {       324}, { 61} }, // constant               
    { {       264}, { 62} }, // NOT                    
    { {       259}, { 45} }, // NAME                   
    { {       257}, { 63} }, // INTEGER_NUMBER         
    { {       258}, { 64} }, // DOUBLE_NUMBER          
    { {         0}, {  0} },                           
};

SR__ s_79[] =
{
    { { REQ_TOKEN}, {  15} },                           
    { {       321}, { 100} }, // operand                
    { {       320}, {  66} }, // arith_expression       
    { {       316}, {  54} }, // boolean_expression_term
    { {        45}, {  55} }, // '-'                    
    { {        40}, {  56} }, // '('                    
    { {       322}, {  57} }, // expression_term        
    { {       318}, {  58} }, // relational_expression  
    { {       317}, {  59} }, // boolean_expression     
    { {       323}, {  60} }, // variable               
    { {       324}, {  61} }, // constant               
    { {       264}, {  62} }, // NOT                    
    { {       259}, {  45} }, // NAME                   
    { {       257}, {  63} }, // INTEGER_NUMBER         
    { {       258}, {  64} }, // DOUBLE_NUMBER          
    { {         0}, {   0} },                           
};

SR__ s_80[] =
{
    { { REQ_TOKEN}, {  15} },                           
    { {       321}, { 101} }, // operand                
    { {       320}, {  66} }, // arith_expression       
    { {       316}, {  54} }, // boolean_expression_term
    { {        45}, {  55} }, // '-'                    
    { {        40}, {  56} }, // '('                    
    { {       322}, {  57} }, // expression_term        
    { {       318}, {  58} }, // relational_expression  
    { {       317}, {  59} }, // boolean_expression     
    { {       323}, {  60} }, // variable               
    { {       324}, {  61} }, // constant               
    { {       264}, {  62} }, // NOT                    
    { {       259}, {  45} }, // NAME                   
    { {       257}, {  63} }, // INTEGER_NUMBER         
    { {       258}, {  64} }, // DOUBLE_NUMBER          
    { {         0}, {   0} },                           
};

SR__ s_81[] =
{
    { { REQ_TOKEN}, {  15} },                           
    { {       321}, { 102} }, // operand                
    { {       320}, {  66} }, // arith_expression       
    { {       316}, {  54} }, // boolean_expression_term
    { {        45}, {  55} }, // '-'                    
    { {        40}, {  56} }, // '('                    
    { {       322}, {  57} }, // expression_term        
    { {       318}, {  58} }, // relational_expression  
    { {       317}, {  59} }, // boolean_expression     
    { {       323}, {  60} }, // variable               
    { {       324}, {  61} }, // constant               
    { {       264}, {  62} }, // NOT                    
    { {       259}, {  45} }, // NAME                   
    { {       257}, {  63} }, // INTEGER_NUMBER         
    { {       258}, {  64} }, // DOUBLE_NUMBER          
    { {         0}, {   0} },                           
};

SR__ s_82[] =
{
    { { REQ_TOKEN}, {  15} },                           
    { {       316}, { 103} }, // boolean_expression_term
    { {       318}, {  58} }, // relational_expression  
    { {       317}, {  59} }, // boolean_expression     
    { {        40}, {  56} }, // '('                    
    { {       321}, {  53} }, // operand                
    { {       264}, {  62} }, // NOT                    
    { {       320}, {  66} }, // arith_expression       
    { {        45}, {  55} }, // '-'                    
    { {       322}, {  57} }, // expression_term        
    { {       323}, {  60} }, // variable               
    { {       324}, {  61} }, // constant               
    { {       259}, {  45} }, // NAME                   
    { {       257}, {  63} }, // INTEGER_NUMBER         
    { {       258}, {  64} }, // DOUBLE_NUMBER          
    { {         0}, {   0} },                           
};

SR__ s_83[] =
{
    { { REQ_TOKEN}, {  15} },                           
    { {       316}, { 104} }, // boolean_expression_term
    { {       318}, {  58} }, // relational_expression  
    { {       317}, {  59} }, // boolean_expression     
    { {        40}, {  56} }, // '('                    
    { {       321}, {  53} }, // operand                
    { {       264}, {  62} }, // NOT                    
    { {       320}, {  66} }, // arith_expression       
    { {        45}, {  55} }, // '-'                    
    { {       322}, {  57} }, // expression_term        
    { {       323}, {  60} }, // variable               
    { {       324}, {  61} }, // constant               
    { {       259}, {  45} }, // NAME                   
    { {       257}, {  63} }, // INTEGER_NUMBER         
    { {       258}, {  64} }, // DOUBLE_NUMBER          
    { {         0}, {   0} },                           
};

SR__ s_84[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -49} }, 
};

SR__ s_85[] =
{
    { { REQ_TOKEN}, {  12} },       
    { {        41}, { 105} }, // ')'
    { {        43}, {  71} }, // '+'
    { {        45}, {  72} }, // '-'
    { {        42}, {  73} }, // '*'
    { {        47}, {  74} }, // '/'
    { {       266}, {  75} }, // LE 
    { {       269}, {  76} }, // LT 
    { {       267}, {  77} }, // EQ 
    { {       268}, {  78} }, // NE 
    { {       265}, {  79} }, // GE 
    { {       270}, {  80} }, // GT 
    { {         0}, {   0} },       
};

SR__ s_86[] =
{
    { { REQ_TOKEN}, {   5} },       
    { {        41}, { 106} }, // ')'
    { {        63}, {  81} }, // '?'
    { {       271}, {  82} }, // AND
    { {       272}, {  83} }, // OR 
    { {         0}, {   0} },       
};

SR__ s_87[] =
{
    { { REQ_DEF}, {   4} },       
    { {     271}, {  82} }, // AND
    { {     272}, {  83} }, // OR 
    { {      63}, {  81} }, // '?'
    { {       0}, { -36} },       
};

SR__ s_88[] =
{
    { { REQ_TOKEN}, {  12} },                        
    { {       314}, { 107} }, // exp_body            
    { {       312}, {  49} }, // statement           
    { {       123}, {  50} }, // '{'                 
    { {       319}, {  38} }, // assignment_statement
    { {       315}, {  39} }, // iteration_statement 
    { {       313}, {  40} }, // selection_statement 
    { {       323}, {  41} }, // variable            
    { {       274}, {  42} }, // WHILE               
    { {       275}, {  43} }, // DO                  
    { {       273}, {  44} }, // IF                  
    { {       259}, {  45} }, // NAME                
    { {         0}, {   0} },                        
};

SR__ s_89[] =
{
    { { REQ_TOKEN}, {  15} },                           
    { {       316}, { 108} }, // boolean_expression_term
    { {       318}, {  58} }, // relational_expression  
    { {       317}, {  59} }, // boolean_expression     
    { {        40}, {  56} }, // '('                    
    { {       321}, {  53} }, // operand                
    { {       264}, {  62} }, // NOT                    
    { {       320}, {  66} }, // arith_expression       
    { {        45}, {  55} }, // '-'                    
    { {       322}, {  57} }, // expression_term        
    { {       323}, {  60} }, // variable               
    { {       324}, {  61} }, // constant               
    { {       259}, {  45} }, // NAME                   
    { {       257}, {  63} }, // INTEGER_NUMBER         
    { {       258}, {  64} }, // DOUBLE_NUMBER          
    { {         0}, {   0} },                           
};

SR__ s_90[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -28} }, 
};

SR__ s_91[] =
{
    { { REQ_TOKEN}, {  12} },                        
    { {       314}, { 109} }, // exp_body            
    { {       312}, {  49} }, // statement           
    { {       123}, {  50} }, // '{'                 
    { {       319}, {  38} }, // assignment_statement
    { {       315}, {  39} }, // iteration_statement 
    { {       313}, {  40} }, // selection_statement 
    { {       323}, {  41} }, // variable            
    { {       274}, {  42} }, // WHILE               
    { {       275}, {  43} }, // DO                  
    { {       273}, {  44} }, // IF                  
    { {       259}, {  45} }, // NAME                
    { {         0}, {   0} },                        
};

SR__ s_92[] =
{
    { { REQ_DEF}, {   3} },       
    { {      42}, {  73} }, // '*'
    { {      47}, {  74} }, // '/'
    { {       0}, { -44} },       
};

SR__ s_93[] =
{
    { { REQ_DEF}, {   3} },       
    { {      42}, {  73} }, // '*'
    { {      47}, {  74} }, // '/'
    { {       0}, { -45} },       
};

SR__ s_94[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -46} }, 
};

SR__ s_95[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -47} }, 
};

SR__ s_96[] =
{
    { { REQ_DEF}, {  11} },       
    { {      43}, {  71} }, // '+'
    { {      45}, {  72} }, // '-'
    { {      42}, {  73} }, // '*'
    { {      47}, {  74} }, // '/'
    { {     266}, {  75} }, // LE 
    { {     269}, {  76} }, // LT 
    { {     267}, {  77} }, // EQ 
    { {     268}, {  78} }, // NE 
    { {     265}, {  79} }, // GE 
    { {     270}, {  80} }, // GT 
    { {       0}, { -37} },       
};

SR__ s_97[] =
{
    { { REQ_DEF}, {  11} },       
    { {      43}, {  71} }, // '+'
    { {      45}, {  72} }, // '-'
    { {      42}, {  73} }, // '*'
    { {      47}, {  74} }, // '/'
    { {     266}, {  75} }, // LE 
    { {     269}, {  76} }, // LT 
    { {     267}, {  77} }, // EQ 
    { {     268}, {  78} }, // NE 
    { {     265}, {  79} }, // GE 
    { {     270}, {  80} }, // GT 
    { {       0}, { -38} },       
};

SR__ s_98[] =
{
    { { REQ_DEF}, {   5} },       
    { {      43}, {  71} }, // '+'
    { {      45}, {  72} }, // '-'
    { {      42}, {  73} }, // '*'
    { {      47}, {  74} }, // '/'
    { {       0}, { -39} },       
};

SR__ s_99[] =
{
    { { REQ_DEF}, {   5} },       
    { {      43}, {  71} }, // '+'
    { {      45}, {  72} }, // '-'
    { {      42}, {  73} }, // '*'
    { {      47}, {  74} }, // '/'
    { {       0}, { -40} },       
};

SR__ s_100[] =
{
    { { REQ_DEF}, {   5} },       
    { {      43}, {  71} }, // '+'
    { {      45}, {  72} }, // '-'
    { {      42}, {  73} }, // '*'
    { {      47}, {  74} }, // '/'
    { {       0}, { -41} },       
};

SR__ s_101[] =
{
    { { REQ_DEF}, {   5} },       
    { {      43}, {  71} }, // '+'
    { {      45}, {  72} }, // '-'
    { {      42}, {  73} }, // '*'
    { {      47}, {  74} }, // '/'
    { {       0}, { -42} },       
};

SR__ s_102[] =
{
    { { REQ_TOKEN}, {  12} },       
    { {        58}, { 110} }, // ':'
    { {        43}, {  71} }, // '+'
    { {        45}, {  72} }, // '-'
    { {        42}, {  73} }, // '*'
    { {        47}, {  74} }, // '/'
    { {       266}, {  75} }, // LE 
    { {       269}, {  76} }, // LT 
    { {       267}, {  77} }, // EQ 
    { {       268}, {  78} }, // NE 
    { {       265}, {  79} }, // GE 
    { {       270}, {  80} }, // GT 
    { {         0}, {   0} },       
};

SR__ s_103[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -34} }, 
};

SR__ s_104[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -35} }, 
};

SR__ s_105[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -50} }, 
};

SR__ s_106[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -33} }, 
};

SR__ s_107[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -29} }, 
};

SR__ s_108[] =
{
    { { REQ_TOKEN}, {   5} },       
    { {        41}, { 111} }, // ')'
    { {       271}, {  82} }, // AND
    { {       272}, {  83} }, // OR 
    { {        63}, {  81} }, // '?'
    { {         0}, {   0} },       
};

SR__ s_109[] =
{
    { { REQ_DEF}, {   2} },        
    { {     276}, { 112} }, // ELSE
    { {       0}, { -25} },        
};

SR__ s_110[] =
{
    { { REQ_TOKEN}, {  15} },                           
    { {       321}, { 113} }, // operand                
    { {       320}, {  66} }, // arith_expression       
    { {       316}, {  54} }, // boolean_expression_term
    { {        45}, {  55} }, // '-'                    
    { {        40}, {  56} }, // '('                    
    { {       322}, {  57} }, // expression_term        
    { {       318}, {  58} }, // relational_expression  
    { {       317}, {  59} }, // boolean_expression     
    { {       323}, {  60} }, // variable               
    { {       324}, {  61} }, // constant               
    { {       264}, {  62} }, // NOT                    
    { {       259}, {  45} }, // NAME                   
    { {       257}, {  63} }, // INTEGER_NUMBER         
    { {       258}, {  64} }, // DOUBLE_NUMBER          
    { {         0}, {   0} },                           
};

SR__ s_111[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -30} }, 
};

SR__ s_112[] =
{
    { { REQ_TOKEN}, {  12} },                        
    { {       314}, { 114} }, // exp_body            
    { {       312}, {  49} }, // statement           
    { {       123}, {  50} }, // '{'                 
    { {       319}, {  38} }, // assignment_statement
    { {       315}, {  39} }, // iteration_statement 
    { {       313}, {  40} }, // selection_statement 
    { {       323}, {  41} }, // variable            
    { {       274}, {  42} }, // WHILE               
    { {       275}, {  43} }, // DO                  
    { {       273}, {  44} }, // IF                  
    { {       259}, {  45} }, // NAME                
    { {         0}, {   0} },                        
};

SR__ s_113[] =
{
    { { REQ_DEF}, {  11} },       
    { {      43}, {  71} }, // '+'
    { {      45}, {  72} }, // '-'
    { {      42}, {  73} }, // '*'
    { {      47}, {  74} }, // '/'
    { {     266}, {  75} }, // LE 
    { {     269}, {  76} }, // LT 
    { {     267}, {  77} }, // EQ 
    { {     268}, {  78} }, // NE 
    { {     265}, {  79} }, // GE 
    { {     270}, {  80} }, // GT 
    { {       0}, { -48} },       
};

SR__ s_114[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -26} }, 
};


// State array:
SR__ *s_state[] =
{
  s_0,  s_1,  s_2,  s_3,  s_4,  s_5,  s_6,  s_7,  s_8,  s_9,
  s_10,  s_11,  s_12,  s_13,  s_14,  s_15,  s_16,  s_17,  s_18,  s_19,
  s_20,  s_21,  s_22,  s_23,  s_24,  s_25,  s_26,  s_27,  s_28,  s_29,
  s_30,  s_31,  s_32,  s_33,  s_34,  s_35,  s_36,  s_37,  s_38,  s_39,
  s_40,  s_41,  s_42,  s_43,  s_44,  s_45,  s_46,  s_47,  s_48,  s_49,
  s_50,  s_51,  s_52,  s_53,  s_54,  s_55,  s_56,  s_57,  s_58,  s_59,
  s_60,  s_61,  s_62,  s_63,  s_64,  s_65,  s_66,  s_67,  s_68,  s_69,
  s_70,  s_71,  s_72,  s_73,  s_74,  s_75,  s_76,  s_77,  s_78,  s_79,
  s_80,  s_81,  s_82,  s_83,  s_84,  s_85,  s_86,  s_87,  s_88,  s_89,
  s_90,  s_91,  s_92,  s_93,  s_94,  s_95,  s_96,  s_97,  s_98,  s_99,
  s_100,  s_101,  s_102,  s_103,  s_104,  s_105,  s_106,  s_107,  s_108,  s_109,
  s_110,  s_111,  s_112,  s_113,  s_114,
};

} // anonymous namespace ends



// If the parsing function call uses arguments, then provide an overloaded
// function.  The code below doesn't rely on parameters, so no arguments are
// required.  Furthermore, parse uses a function try block to allow us to do
// ACCEPT and ABORT from anywhere, even from within members called by actions,
// simply throwing the appropriate exceptions.

ParserBase::ParserBase()
:
    d_stackIdx__(-1),
    // $insert debuginit
    d_debug__(false),
    d_nErrors__(0),
    // $insert requiredtokens
    d_requiredTokens__(0),
    d_acceptedTokens__(d_requiredTokens__),
    d_token__(_UNDETERMINED_),
    d_nextToken__(_UNDETERMINED_)
{}


void Parser::print__()
{
// $insert print
}

void ParserBase::clearin()
{
    d_token__ = d_nextToken__ = _UNDETERMINED_;
}

void ParserBase::push__(size_t state)
{
    if (static_cast<size_t>(d_stackIdx__ + 1) == d_stateStack__.size())
    {
        size_t newSize = d_stackIdx__ + STACK_EXPANSION;
        d_stateStack__.resize(newSize);
        d_valueStack__.resize(newSize);
    }
    ++d_stackIdx__;
    d_stateStack__[d_stackIdx__] = d_state__ = state;
    *(d_vsp__ = &d_valueStack__[d_stackIdx__]) = d_val__;
}

void ParserBase::popToken__()
{
    d_token__ = d_nextToken__;

    d_val__ = d_nextVal__;
    d_nextVal__ = STYPE__();

    d_nextToken__ = _UNDETERMINED_;
}
     
void ParserBase::pushToken__(int token)
{
    d_nextToken__ = d_token__;
    d_nextVal__ = d_val__;
    d_token__ = token;
}
     
void ParserBase::pop__(size_t count)
{
    if (d_stackIdx__ < static_cast<int>(count))
    {
        ABORT();
    }

    d_stackIdx__ -= count;
    d_state__ = d_stateStack__[d_stackIdx__];
    d_vsp__ = &d_valueStack__[d_stackIdx__];
}

inline size_t ParserBase::top__() const
{
    return d_stateStack__[d_stackIdx__];
}

void Parser::executeAction(int production)
try
{
    if (d_token__ != _UNDETERMINED_)
        pushToken__(d_token__);     // save an already available token

// $insert defaultactionreturn
                            // save default non-nested block $$
    if (int size = s_productionInfo[production].d_size)
        d_val__ = d_vsp__[1 - size];

    switch (production)
    {
        // $insert actioncases
        
        case 1:
#line 69 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         CHECK_INVARIANT((current_procedure != NULL), "Current procedure cannot be null");
         program_object.set_procedure(current_procedure, get_line_number());
         program_object.global_list_in_proc_check();
         }
         }
        break;

        case 2:
#line 82 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         Symbol_Table * global_table = new Symbol_Table();
         program_object.set_global_table(*global_table);
         }
         }
        break;

        case 3:
#line 92 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         Symbol_Table * global_table = d_vsp__[-1].symbol_table;
         CHECK_INVARIANT((global_table != NULL), "Global declarations cannot be null");
         program_object.set_global_table(*global_table);
         }
         }
        break;

        case 4:
#line 105 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         Symbol_Table * global_table = d_vsp__[0].symbol_table;
         CHECK_INVARIANT((global_table != NULL), "Global declarations cannot be null");
         program_object.set_global_table(*global_table);
         }
         }
        break;

        case 5:
#line 119 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         CHECK_INVARIANT((d_vsp__[-3].string_value != NULL), "Procedure name cannot be null");
         CHECK_INVARIANT((*d_vsp__[-3].string_value == "main"), "Procedure name must be main in declaration");
         }
         }
        break;

        case 6:
#line 162 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         Sequence_Ast* seq = d_vsp__[-1].sequence_ast;
         CHECK_INVARIANT((current_procedure != NULL), "Current procedure cannot be null");
         CHECK_INVARIANT((seq != NULL), "statement list cannot be null");
         current_procedure->set_sequence_ast(*seq);
         }
         }
        break;

        case 7:
#line 130 "parser.yy"
        d_val__ = d_vsp__[-2];
        {
         if (NOT_ONLY_PARSE)
         {
         CHECK_INVARIANT((d_vsp__[-2].string_value != NULL), "Procedure name cannot be null");
         CHECK_INVARIANT((*d_vsp__[-2].string_value == "main"), "Procedure name must be main");
         string proc_name = *d_vsp__[-2].string_value;
         current_procedure = new Procedure(void_data_type, proc_name, get_line_number());
         CHECK_INPUT ((program_object.variable_in_symbol_list_check(proc_name) == false),
         "Procedure name cannot be same as global variable", get_line_number());
         }
         }
        break;

        case 8:
#line 146 "parser.yy"
        d_val__ = d_vsp__[-5];
        {
         if (NOT_ONLY_PARSE)
         {
         CHECK_INVARIANT((current_procedure != NULL), "Current procedure cannot be null");
         Symbol_Table * local_table = d_vsp__[0].symbol_table;
         if (local_table == NULL)
         local_table = new Symbol_Table();
         current_procedure->set_local_list(*local_table);
         }
         }
        break;

        case 9:
#line 176 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         d_val__.symbol_table = NULL;
         }
         }
        break;

        case 10:
#line 184 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         CHECK_INVARIANT((d_vsp__[0].symbol_table != NULL), "Declaration statement list cannot be null here");
         
         d_val__.symbol_table = d_vsp__[0].symbol_table;
         }
         }
        break;

        case 11:
#line 196 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         CHECK_INVARIANT((d_vsp__[0].list_symbol_entry != NULL), "Non-terminal declaration statement cannot be null");
         
         Symbol_Table * decl_list = new Symbol_Table();
         
         for(list<Symbol_Table_Entry *>::iterator it=d_vsp__[0].list_symbol_entry->begin(); it!=d_vsp__[0].list_symbol_entry->end(); ++it){
         string decl_name = (*it)->get_variable_name();
         CHECK_INPUT ((program_object.variable_proc_name_check(decl_name) == false),
         "Variable name cannot be same as the procedure name", get_line_number());
         if(current_procedure != NULL)
         {
         CHECK_INPUT((current_procedure->get_proc_name() != decl_name),
         "Variable name cannot be same as procedure name", get_line_number());
         }
         CHECK_INPUT((decl_list->variable_in_symbol_list_check(decl_name) == false), 
         "Variable is declared twice", get_line_number());
         
         decl_list->push_symbol(*it);
         
         }
         d_val__.symbol_table = decl_list;
         }
         }
        break;

        case 12:
#line 226 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         
         
         CHECK_INVARIANT((d_vsp__[0].list_symbol_entry != NULL), "The declaration statement cannot be null");
         CHECK_INVARIANT((d_vsp__[-1].symbol_table != NULL), "The declaration statement list cannot be null");
         
         
         
         for(list<Symbol_Table_Entry *>::iterator it=d_vsp__[0].list_symbol_entry->begin(); it!=d_vsp__[0].list_symbol_entry->end(); ++it){
         string decl_name = (*it)->get_variable_name();
         CHECK_INPUT((program_object.variable_proc_name_check(decl_name) == false),
         "Procedure name cannot be same as the variable name", get_line_number());
         if(current_procedure != NULL)
         {
         CHECK_INPUT((current_procedure->get_proc_name() != decl_name),
         "Variable name cannot be same as procedure name", get_line_number());
         }
         CHECK_INPUT((d_vsp__[-1].symbol_table->variable_in_symbol_list_check(decl_name) == false), 
         "Variable is declared twice", get_line_number());
         
         d_vsp__[-1].symbol_table->push_symbol(*it);
         
         }
         
         d_val__.symbol_table = d_vsp__[-1].symbol_table;
         }
         }
        break;

        case 13:
#line 261 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         
         
         list<Symbol_Table_Entry *> * list_ste = new list<Symbol_Table_Entry *>;
         
         CHECK_INVARIANT((d_vsp__[-1].list_decl != NULL), "Pointer to list of pair of declarations cannot be null");
         for(list<pair<Data_Type, string> *>::iterator it=d_vsp__[-1].list_decl->begin(); it!=d_vsp__[-1].list_decl->end(); ++it){
         Data_Type type = (*it)->first;
         string decl_name = (*it)->second;
         Symbol_Table_Entry * decl_entry = new Symbol_Table_Entry(decl_name, type, get_line_number());
         list_ste->push_back(decl_entry);
         
         }
         
         d_val__.list_symbol_entry = list_ste; 
         }
         }
        break;

        case 14:
#line 285 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         
         CHECK_INVARIANT((d_vsp__[0].list_decl != NULL), "int_declaration_names_list cannot be null");
         
         
         d_val__.list_decl = d_vsp__[0].list_decl; 
         }
         }
        break;

        case 15:
#line 297 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         
         CHECK_INVARIANT((d_vsp__[0].list_decl != NULL), "float_declaration_names_list cannot be null");
         
         
         d_val__.list_decl = d_vsp__[0].list_decl;
         }
         }
        break;

        case 16:
#line 311 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         
         CHECK_INVARIANT((d_vsp__[0].string_value != NULL), "Name cannot be null");
         string name = *d_vsp__[0].string_value;
         Data_Type type = int_data_type;
         pair<Data_Type, string> * declar = new pair<Data_Type, string>(type, name);
         list<pair<Data_Type, string> *> * int_list_pairs = new list<pair<Data_Type, string> *>;
         int_list_pairs->push_back(declar);
         
         d_val__.list_decl = int_list_pairs;
         }
         }
        break;

        case 17:
#line 327 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         
         CHECK_INVARIANT((d_vsp__[-2].list_decl != NULL), "Name list cannot be null");
         string name = *d_vsp__[0].string_value;
         Data_Type type = int_data_type;
         
         pair<Data_Type, string> * declar = new pair<Data_Type, string>(type, name);
         d_vsp__[-2].list_decl->push_back(declar);
         
         d_val__.list_decl = d_vsp__[-2].list_decl;
         }
         }
        break;

        case 18:
#line 345 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         
         CHECK_INVARIANT((d_vsp__[0].string_value != NULL), "Name cannot be null");
         string name = *d_vsp__[0].string_value;
         Data_Type type = double_data_type;
         pair<Data_Type, string> * declar = new pair<Data_Type, string>(type, name);
         list<pair<Data_Type, string> *> * float_list_pairs = new list<pair<Data_Type, string> *>;
         float_list_pairs->push_back(declar);
         
         d_val__.list_decl = float_list_pairs;
         }
         }
        break;

        case 19:
#line 361 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         
         CHECK_INVARIANT((d_vsp__[-2].list_decl != NULL), "Name list cannot be null");
         string name = *d_vsp__[0].string_value;
         Data_Type type = double_data_type;
         
         pair<Data_Type, string> * declar = new pair<Data_Type, string>(type, name);
         d_vsp__[-2].list_decl->push_back(declar);
         
         d_val__.list_decl = d_vsp__[-2].list_decl;
         }
         }
        break;

        case 20:
#line 378 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         
         
         Sequence_Ast * stmt_list = new Sequence_Ast(get_line_number());
         d_val__.sequence_ast = stmt_list;
         }
         }
        break;

        case 21:
#line 389 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         
         
         Ast * stmt = d_vsp__[0].ast;
         Sequence_Ast * stmt_list = d_vsp__[-1].sequence_ast;
         if(stmt_list == NULL)
         {
         stmt_list = new Sequence_Ast(get_line_number());
         }
         stmt_list->ast_push_back(stmt);
         d_val__.sequence_ast = stmt_list;
         }
         }
        break;

        case 22:
#line 409 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         d_val__.ast = d_vsp__[0].ast;
         }
         }
        break;

        case 23:
#line 417 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         d_val__.ast = d_vsp__[0].ast;
         }
         }
        break;

        case 24:
#line 425 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         d_val__.ast = d_vsp__[0].ast;
         }
         }
        break;

        case 25:
#line 435 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         
         Ast * slt_stmt = new Selection_Statement_Ast(d_vsp__[-2].ast, d_vsp__[0].ast, new Sequence_Ast(get_line_number()), get_line_number());
         d_val__.ast = slt_stmt;
         }
         }
        break;

        case 26:
#line 445 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         
         CHECK_INVARIANT((d_vsp__[0].ast!=NULL),"else part cannot be null");
         Ast * slt_stmt = new Selection_Statement_Ast(d_vsp__[-4].ast, d_vsp__[-2].ast, d_vsp__[0].ast, get_line_number());
         d_val__.ast = slt_stmt;
         }
         }
        break;

        case 27:
#line 479 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         d_val__.ast = d_vsp__[0].ast;
         }
         }
        break;

        case 28:
#line 487 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         d_val__.ast = d_vsp__[-1].sequence_ast;
         }
         }
        break;

        case 29:
#line 497 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         Ast *it_stmt = new Iteration_Statement_Ast(d_vsp__[-2].ast, d_vsp__[0].ast, get_line_number(), false);
         d_val__.ast = it_stmt;
         }
         }
        break;

        case 30:
#line 506 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         Ast *it_stmt = new Iteration_Statement_Ast(d_vsp__[-1].ast, d_vsp__[-4].ast, get_line_number(), true);
         d_val__.ast = it_stmt;
         }
         }
        break;

        case 31:
#line 518 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         
         d_val__.ast = d_vsp__[0].ast;
         }
         }
        break;

        case 32:
#line 527 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         
         d_val__.ast = d_vsp__[0].ast;
         }
         }
        break;

        case 33:
#line 536 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         d_val__.ast = d_vsp__[-1].ast;
         }
         }
        break;

        case 34:
#line 546 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         Boolean_Op bop = boolean_and;
         Ast * bool_exp = new Boolean_Expr_Ast(d_vsp__[-2].ast, bop, d_vsp__[0].ast, get_line_number());
         d_val__.ast = bool_exp;
         }
         }
        break;

        case 35:
#line 556 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         Boolean_Op bop = boolean_or;
         Ast *bool_exp = new Boolean_Expr_Ast(d_vsp__[-2].ast, bop, d_vsp__[0].ast, get_line_number());
         d_val__.ast = bool_exp;
         }
         }
        break;

        case 36:
#line 566 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         Boolean_Op bop = boolean_not;
         Ast *bool_exp = new Boolean_Expr_Ast(d_vsp__[0].ast, bop, NULL, get_line_number());
         d_val__.ast = bool_exp;
         }
         }
        break;

        case 37:
#line 578 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         Relational_Op rop = less_equalto;
         Ast *rel_exp = new Relational_Expr_Ast(d_vsp__[-2].ast, rop, d_vsp__[0].ast, get_line_number());
         d_val__.ast = rel_exp;
         }
         }
        break;

        case 38:
#line 588 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         Relational_Op rop = less_than;
         Ast *rel_exp = new Relational_Expr_Ast(d_vsp__[-2].ast, rop, d_vsp__[0].ast, get_line_number());
         d_val__.ast = rel_exp;
         }
         }
        break;

        case 39:
#line 598 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         Relational_Op rop = equalto;
         Ast *rel_exp = new Relational_Expr_Ast(d_vsp__[-2].ast, rop, d_vsp__[0].ast, get_line_number());
         d_val__.ast = rel_exp;
         }
         }
        break;

        case 40:
#line 608 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         Relational_Op rop = not_equalto;
         Ast *rel_exp = new Relational_Expr_Ast(d_vsp__[-2].ast, rop, d_vsp__[0].ast, get_line_number());
         d_val__.ast = rel_exp;
         }
         }
        break;

        case 41:
#line 618 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         Relational_Op rop = greater_equalto;
         Ast *rel_exp = new Relational_Expr_Ast(d_vsp__[-2].ast, rop, d_vsp__[0].ast, get_line_number());
         d_val__.ast = rel_exp;
         }
         }
        break;

        case 42:
#line 628 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         Relational_Op rop = greater_than;
         Ast *rel_exp = new Relational_Expr_Ast(d_vsp__[-2].ast, rop, d_vsp__[0].ast, get_line_number());
         d_val__.ast = rel_exp;
         }
         }
        break;

        case 43:
#line 642 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         
         CHECK_INVARIANT(((d_vsp__[-3].ast != NULL) && (d_vsp__[-1].ast != NULL)), "lhs/rhs cannot be null");
         
         Ast *ast_stmt = new Assignment_Ast(d_vsp__[-3].ast, d_vsp__[-1].ast, get_line_number());
         ast_stmt->check_ast();
         d_val__.ast = ast_stmt;
         }
         }
        break;

        case 44:
#line 663 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         Ast *arith_stmt = new Plus_Ast(d_vsp__[-2].ast, d_vsp__[0].ast, get_line_number());
         arith_stmt->check_ast();
         d_val__.ast = arith_stmt;
         }
         }
        break;

        case 45:
#line 673 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         Ast *arith_stmt = new Minus_Ast(d_vsp__[-2].ast, d_vsp__[0].ast, get_line_number());
         arith_stmt->check_ast();
         d_val__.ast = arith_stmt;
         }
         }
        break;

        case 46:
#line 683 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         Ast *arith_stmt = new Mult_Ast(d_vsp__[-2].ast, d_vsp__[0].ast, get_line_number());
         arith_stmt->check_ast();
         d_val__.ast = arith_stmt;
         }
         }
        break;

        case 47:
#line 693 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         Ast *arith_stmt = new Divide_Ast(d_vsp__[-2].ast, d_vsp__[0].ast, get_line_number());
         arith_stmt->check_ast();
         d_val__.ast = arith_stmt;
         }
         }
        break;

        case 48:
#line 703 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         CHECK_INVARIANT((d_vsp__[-4].ast != NULL), "boolean_expression_term cannot be null");
         CHECK_INVARIANT((d_vsp__[-2].ast != NULL), "operand cannot be null");
         CHECK_INVARIANT((d_vsp__[0].ast != NULL), "operand cannot be null");
         Ast *arith_stmt = new Conditional_Operator_Ast(d_vsp__[-4].ast, d_vsp__[-2].ast, d_vsp__[0].ast, get_line_number());
         d_val__.ast = arith_stmt;
         }
         }
        break;

        case 49:
#line 715 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         CHECK_INVARIANT((d_vsp__[0].ast!=NULL), "operand cannot be NULL");
         Ast *arith_stmt = new UMinus_Ast(d_vsp__[0].ast, NULL, get_line_number());
         d_val__.ast = arith_stmt;
         }
         }
        break;

        case 50:
#line 725 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         d_val__.ast = d_vsp__[-1].ast;
         }
         }
        break;

        case 51:
#line 733 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         d_val__.ast = d_vsp__[0].ast;
         }
         }
        break;

        case 52:
#line 743 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         
         CHECK_INVARIANT((d_vsp__[0].ast != NULL), "Arith expression cannot be null");
         d_val__.ast = d_vsp__[0].ast;
         }
         }
        break;

        case 53:
#line 755 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         
         CHECK_INVARIANT((d_vsp__[0].ast != NULL), "Variable cannot be null");
         d_val__.ast = d_vsp__[0].ast;
         }
         }
        break;

        case 54:
#line 765 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         
         CHECK_INVARIANT((d_vsp__[0].ast != NULL), "constant cannot be null");
         d_val__.ast = d_vsp__[0].ast;
         }
         }
        break;

        case 55:
#line 777 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         Symbol_Table_Entry * var_table_entry;
         CHECK_INVARIANT((d_vsp__[0].string_value != NULL), "Variable name cannot be null");
         if (current_procedure->variable_in_symbol_list_check(*d_vsp__[0].string_value))
         var_table_entry = &(current_procedure->get_symbol_table_entry(*d_vsp__[0].string_value));
         else if (program_object.variable_in_symbol_list_check(*d_vsp__[0].string_value))
         var_table_entry = &(program_object.get_symbol_table_entry(*d_vsp__[0].string_value));
         else
         CHECK_INPUT_AND_ABORT(CONTROL_SHOULD_NOT_REACH, "Variable has not been declared", get_line_number());
         d_val__.ast = new Name_Ast(*d_vsp__[0].string_value, *var_table_entry, get_line_number());
         delete d_vsp__[0].string_value;
         }
         }
        break;

        case 56:
#line 801 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         
         Ast * num_ast = new Number_Ast<int>(d_vsp__[0].integer_value, int_data_type, get_line_number());
         d_val__.ast = num_ast;
         }
         }
        break;

        case 57:
#line 811 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         
         Ast * num_ast = new Number_Ast<double>(d_vsp__[0].double_value, double_data_type, get_line_number());
         d_val__.ast = num_ast;
         }
         }
        break;

    }
}
catch (std::exception const &exc)
{
    exceptionHandler__(exc);
}

inline void ParserBase::reduce__(PI__ const &pi)
{
    d_token__ = pi.d_nonTerm;
    pop__(pi.d_size);

}

// If d_token__ is _UNDETERMINED_ then if d_nextToken__ is _UNDETERMINED_ another
// token is obtained from lex(). Then d_nextToken__ is assigned to d_token__.
void Parser::nextToken()
{
    if (d_token__ != _UNDETERMINED_)        // no need for a token: got one
        return;                             // already

    if (d_nextToken__ != _UNDETERMINED_)
    {
        popToken__();                       // consume pending token
    }
    else
    {
        ++d_acceptedTokens__;               // accept another token (see
                                            // errorRecover())
        d_token__ = lex();
        if (d_token__ <= 0)
            d_token__ = _EOF_;
    }
    print();
}

// if the final transition is negative, then we should reduce by the rule
// given by its positive value. Note that the `recovery' parameter is only
// used with the --debug option
int Parser::lookup(bool recovery)
{
// $insert threading
    SR__ *sr = s_state[d_state__];          // get the appropriate state-table
    int lastIdx = sr->d_lastIdx;            // sentinel-index in the SR__ array
    
    SR__ *lastElementPtr = sr + lastIdx;
    lastElementPtr->d_token = d_token__;    // set search-token
    
    SR__ *elementPtr = sr + 1;              // start the search at s_xx[1]
    while (elementPtr->d_token != d_token__)
        ++elementPtr;
    

    if (elementPtr == lastElementPtr)   // reached the last element
    {
        if (elementPtr->d_action < 0)   // default reduction
        {
            return elementPtr->d_action;                
        }

        // No default reduction, so token not found, so error.
        throw UNEXPECTED_TOKEN__;
    }

    // not at the last element: inspect the nature of the action
    // (< 0: reduce, 0: ACCEPT, > 0: shift)

    int action = elementPtr->d_action;


    return action;
}

    // When an error has occurred, pop elements off the stack until the top
    // state has an error-item. If none is found, the default recovery
    // mode (which is to abort) is activated. 
    //
    // If EOF is encountered without being appropriate for the current state,
    // then the error recovery will fall back to the default recovery mode.
    // (i.e., parsing terminates)
void Parser::errorRecovery()
try
{
    if (d_acceptedTokens__ >= d_requiredTokens__)// only generate an error-
    {                                           // message if enough tokens 
        ++d_nErrors__;                          // were accepted. Otherwise
        error("Syntax error");                  // simply skip input

    }


    // get the error state
    while (not (s_state[top__()][0].d_type & ERR_ITEM))
    {
        pop__();
    }

    // In the error state, lookup a token allowing us to proceed.
    // Continuation may be possible following multiple reductions,
    // but eventuall a shift will be used, requiring the retrieval of
    // a terminal token. If a retrieved token doesn't match, the catch below 
    // will ensure the next token is requested in the while(true) block
    // implemented below:

    int lastToken = d_token__;                  // give the unexpected token a
                                                // chance to be processed
                                                // again.

    pushToken__(_error_);                       // specify _error_ as next token
    push__(lookup(true));                       // push the error state

    d_token__ = lastToken;                      // reactivate the unexpected
                                                // token (we're now in an
                                                // ERROR state).

    bool gotToken = true;                       // the next token is a terminal

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
            {
                gotToken = d_token__ == _UNDETERMINED_;
                nextToken();                    // obtain next token
            }
            
            int action = lookup(true);

            if (action > 0)                 // push a new state
            {
                push__(action);
                popToken__();

                if (gotToken)
                {

                    d_acceptedTokens__ = 0;
                    return;
                }
            }
            else if (action < 0)
            {
                // no actions executed on recovery but save an already 
                // available token:
                if (d_token__ != _UNDETERMINED_)
                    pushToken__(d_token__);
 
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else
                ABORT();                    // abort when accepting during
                                            // error recovery
        }
        catch (...)
        {
            if (d_token__ == _EOF_)
                ABORT();                    // saw inappropriate _EOF_
                      
            popToken__();                   // failing token now skipped
        }
    }
}
catch (ErrorRecovery__)       // This is: DEFAULT_RECOVERY_MODE
{
    ABORT();
}

    // The parsing algorithm:
    // Initially, state 0 is pushed on the stack, and d_token__ as well as
    // d_nextToken__ are initialized to _UNDETERMINED_. 
    //
    // Then, in an eternal loop:
    //
    //  1. If a state does not have REQ_TOKEN no token is assigned to
    //     d_token__. If the state has REQ_TOKEN, nextToken() is called to
    //      determine d_nextToken__ and d_token__ is set to
    //     d_nextToken__. nextToken() will not call lex() unless d_nextToken__ is 
    //     _UNDETERMINED_. 
    //
    //  2. lookup() is called: 
    //     d_token__ is stored in the final element's d_token field of the
    //     state's SR_ array. 
    //
    //  3. The current token is looked up in the state's SR_ array
    //
    //  4. Depending on the result of the lookup() function the next state is
    //     shifted on the parser's stack, a reduction by some rule is applied,
    //     or the parsing function returns ACCEPT(). When a reduction is
    //     called for, any action that may have been defined for that
    //     reduction is executed.
    //
    //  5. An error occurs if d_token__ is not found, and the state has no
    //     default reduction. Error handling was described at the top of this
    //     file.

int Parser::parse()
try 
{
    push__(0);                              // initial state
    clearin();                              // clear the tokens.

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
                nextToken();                // obtain next token


            int action = lookup(false);     // lookup d_token__ in d_state__

            if (action > 0)                 // SHIFT: push a new state
            {
                push__(action);
                popToken__();               // token processed
            }
            else if (action < 0)            // REDUCE: execute and pop.
            {
                executeAction(-action);
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else 
                ACCEPT();
        }
        catch (ErrorRecovery__)
        {
            errorRecovery();
        }
    }
}
catch (Return__ retValue)
{
    return retValue;
}



